#!/bin/bash

set -ouex pipefail

# Repo cleanup
rm -rf /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:phracek:PyCharm.repo 
rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo 
rm -rf /etc/yum.repos.d/google-chrome.repo 
rm -rf /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo 
rm -rf /etc/yum.repos.d/rpmfusion-nonfree-steam.repo 
# DNF auto updates
sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf 
systemctl enable rpm-ostreed-automatic.timer || true 
dnf -y install tailscale 
systemctl enable tailscaled.service || true 
systemctl enable sshd.service || true 
# Debloat
dnf -y remove firefox* gnome-shell-extension* gnome-tour yelp* gnome-software-rpm-ostree virtualbox-guest-additions malcontent-control fedora-chromium-config* 