#!/bin/bash
set -ouexv pipefail

#-----------------------#

# Tailscale
dnf install -y tailscale 
systemctl enable tailscaled.service
# SSH
dnf install -y openssh
systemctl enable sshd.service

#-----------------------#

#dnf group list --hidden --installed | sort
#dnf group list --hidden | sort

#rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo

# System auto updates
#sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf 
#systemctl enable rpm-ostreed-automatic.timer || true 

#cat /etc/rpm-ostreed.conf 
#cat /etc/systemd/system/timers.target.wants/rpm-ostreed-automatic.timer
#cat /usr/lib/systemd/system/rpm-ostreed-automatic.timer

# cat /usr/lib/systemd/system/bootc-fetch-apply-updates.service
#[Unit]
#Description=Apply bootc updates
#Documentation=man:bootc(8)
#ConditionPathExists=/run/ostree-booted
#[Service]
#Type=oneshot
#ExecStart=/usr/bin/bootc update --apply --quiet

# cat /usr/lib/systemd/system/bootc-fetch-apply-updates.timer
#[Unit]
#Description=Apply bootc updates
#Documentation=man:bootc(8)
#ConditionPathExists=/run/ostree-booted

#[Timer]
# Disable the automatic reboot on the update service for bootc
#OnBootSec=1h
# This time is relatively arbitrary and obviously expected to be overridden/changed
#OnUnitInactiveSec=8h
# When deploying a large number of systems, it may be beneficial to increase this value to help with load on the registry.
#RandomizedDelaySec=2h
#[Install]
#WantedBy=timers.target

# /*
# Configure Updates
# */
#sed -i 's|^ExecStart=.*|ExecStart=/usr/bin/bootc update --quiet|' /usr/lib/systemd/system/bootc-fetch-apply-updates.service
#sed -i 's|^OnUnitInactiveSec=.*|OnUnitInactiveSec=7d\nPersistent=true|' /usr/lib/systemd/system/bootc-fetch-apply-updates.timer
#sed -i 's|#AutomaticUpdatePolicy.*|AutomaticUpdatePolicy=stage|' /etc/rpm-ostreed.conf
#sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf
#cat /usr/lib/systemd/system/bootc-fetch-apply-updates.service
#cat /usr/lib/systemd/system/bootc-fetch-apply-updates.timer


# Disable the automatic reboot on the update service for bootc
#mkdir -p /etc/systemd/system/bootc-fetch-apply-updates.service.d
#cat << EOF > /etc/systemd/system/bootc-fetch-apply-updates.service.d/10-no-apply.conf
#[Service]
#ExecStart=
#ExecStart=/usr/bin/bootc update --quiet
#EOF

# Firewall
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable firewalld
#systemctl enable firewalld.service || true 

# Tailscale
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable tailscale 
#systemctl enable tailscaled.service || true 

# SSH
#systemctl enable sshd.service || true 

# Cockpit - basic only
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable cockpit #cockpit-machines cockpit-podman cockpit-files cockpit-navigator cockpit-selinux
#systemctl enable cockpit.socket || true

# Common packages
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable git
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable rsync

# Toolbox to Distrobox
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable distrobox
##dnf remove -y toolbox

#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable \
#bash-completion \
#tuned tuned-ppd \
#syncthing 

# Repo cleanup
#rm -rf /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:phracek:PyCharm.repo
#rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo
#rm -rf /etc/yum.repos.d/google-chrome.repo
#rm -rf /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
#rm -rf /etc/yum.repos.d/rpmfusion-nonfree-steam.repo
# DNF auto updates
#sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf
#systemctl enable rpm-ostreed-automatic.timer || true
#dnf -y install tailscale git
#systemctl enable tailscaled.service || true
#systemctl enable sshd.service || true
# Debloat
#dnf -y remove firefox* gnome-shell-extension* gnome-tour yelp* gnome-software-rpm-ostree virtualbox-guest-additions malcontent-control fedora-chromium-config*
