#!/bin/bash
set -ouexv pipefail

rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo

# System auto updates
sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf 
systemctl enable rpm-ostreed-automatic.timer || true 

# Tailscale
dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable tailscale 
systemctl enable tailscaled.service || true 

# SSH
systemctl enable sshd.service || true 

# Cockpit - basic only
dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable cockpit #cockpit-machines cockpit-podman cockpit-files cockpit-navigator cockpit-selinux
systemctl enable cockpit.socket || true

# Common packages
dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable git
dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable rsync

# Toolbox to Distrobox
dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable distrobox
#dnf remove -y toolbox

# Repo cleanup
#rm -rf /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:phracek:PyCharm.repo
#rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo
#rm -rf /etc/yum.repos.d/google-chrome.repo
#rm -rf /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
#rm -rf /etc/yum.repos.d/rpmfusion-nonfree-steam.repo
# DNF auto updates
#sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf
#systemctl enable rpm-ostreed-automatic.timer || true
#dnf -y install tailscale git
#systemctl enable tailscaled.service || true
#systemctl enable sshd.service || true
# Debloat
#dnf -y remove firefox* gnome-shell-extension* gnome-tour yelp* gnome-software-rpm-ostree virtualbox-guest-additions malcontent-control fedora-chromium-config*
