#!/bin/bash
set -ouex pipefail

#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  base-graphical
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  container-management
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  core
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  fonts
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  gnome-desktop
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  guest-desktop-agents
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  hardware-support
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  multimedia
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  networkmanager-submodules
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  printing
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  workstation-product
#dnf group install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable  virtualization 

#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable fedora-release-silverblue
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable fedora-release-ostree-desktop
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable flatpak
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable gnome-shell gnome-control-center
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable gdm
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable gnome-system-monitor gnome-software
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable gnome-disk-utility
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable nautilus
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable ptyxis
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable adw-gtk3-theme
#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable tuned tuned-ppd

# Gnome desktop
#dnf install -y --setopt=install_weak_deps=False \
#gdm \
#gnome-shell \
#&& \
#dnf clean all && rm -rf /var/cache/libdnf5

dnf install -y --setopt=install_weak_deps=False flatpak
dnf install -y --setopt=install_weak_deps=False gnome-shell
dnf install -y --setopt=install_weak_deps=False gdm
dnf install -y --setopt=install_weak_deps=False gnome-system-monitor gnome-software gnome-disk-utility
dnf install -y --setopt=install_weak_deps=False gnome-control-center
dnf install -y --setopt=install_weak_deps=False nautilus
dnf install -y --setopt=install_weak_deps=False ptyxis
dnf install -y --setopt=install_weak_deps=False adw-gtk3-theme
dnf install -y --setopt=install_weak_deps=False tuned tuned-ppd



dnf install -y --setopt=install_weak_deps=False pipewire
dnf install -y --setopt=install_weak_deps=False pipewire-libs
dnf install -y --setopt=install_weak_deps=False pipewire-pulseaudio
dnf install -y --setopt=install_weak_deps=False pipewire-utils
dnf install -y --setopt=install_weak_deps=False pipewire-alsa
dnf install -y --setopt=install_weak_deps=False pipewire-gstreamer
dnf install -y --setopt=install_weak_deps=False pipewire-plugin-libcamera
dnf install -y --setopt=install_weak_deps=False pipewire-jack-audio-connection-kit
dnf install -y --setopt=install_weak_deps=False pipewire-jack-audio-connection-kit-libs
dnf install -y --setopt=install_weak_deps=False pulseaudio-utils
dnf install -y --setopt=install_weak_deps=False pulseaudio-libs
dnf install -y --setopt=install_weak_deps=False pulseaudio-libs-glib2
dnf install -y --setopt=install_weak_deps=False wireplumber
dnf install -y --setopt=install_weak_deps=False wireplumber-libs
dnf install -y --setopt=install_weak_deps=False alsa-lib
dnf install -y --setopt=install_weak_deps=False alsa-ucm
dnf install -y --setopt=install_weak_deps=False alsa-utils
dnf install -y --setopt=install_weak_deps=False alsa-sof-firmware









systemctl set-default graphical.target

# Flatpak setup
#echo -e "[Unit]\nDescription=Update Flatpaks\n[Service]\nType=oneshot\nExecStart=/usr/bin/flatpak remote-modify --disable fedora ; /usr/bin/flatpak remote-modify --enable flathub ; /usr/bin/flatpak uninstall --unused -y --noninteractive ; /usr/bin/bash -c 'curl -sSL https://raw.githubusercontent.com/emblem-66/Linux-Stuff/refs/heads/main/flatpak.list | xargs -r flatpak install -y --noninteractive' ; /usr/bin/bash -c 'cat ~/.flatpak-apps.list | xargs -r flatpak install -y --noninteractive' ; /usr/bin/flatpak update -y --noninteractive\n[Install]\nWantedBy=default.target\n" | tee /etc/systemd/system/flatpak-update.service
#echo -e "[Unit]\nDescription=Update Flatpaks\n[Timer]\nOnCalendar=*:0/4\nPersistent=true\n[Install]\nWantedBy=timers.target\n" | tee /etc/systemd/system/flatpak-update.timer
#systemctl enable flatpak-update.timer || true
# Morewaita Icons
#git clone https://github.com/somepaulo/MoreWaita.git /usr/share/icons/MoreWaita/
# Gsettings
#gsettings set org.gnome.desktop.wm.preferences resize-with-right-button "true"

#rpm -qa | sort

rpm -qa | sort | grep kernel
rpm -qa | sort | grep gnome
rpm -qa | sort | grep mesa
rpm -qa | sort | grep xdg-user-dirs
