#!/bin/bash

set -ouex pipefail


dnf -y install smartmontools libvirt cockpit cockpit-machines cockpit-podman cockpit-files cockpit-navigator cockpit-selinux
systemctl enable cockpit.socket || true
systemctl enable libvirtd || true
systemctl enable httpd.service || true
