#!/bin/bash
set -ouex pipefail

dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable NetworkManager
dnf install --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable -y cockpit* #cockpit-machines cockpit-podman cockpit-files cockpit-navigator cockpit-selinux

dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable podman podman-compose

systemctl enable cockpit.socket || true
#systemctl enable libvirtd || true
#systemctl enable httpd.service || true

rpm -qa | sort | grep cockpit

# rpm-fusion
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

dnf install -y --allowerasing libavcodec-freeworld mesa*freeworld ffmpeg gstreamer*

dnf install -y jellyfin*
systemctl enable jellyfin




#transmission

#https://linuxcapable.com/how-to-install-transmission-on-fedora-linux/