#!/bin/bash
set -ouex pipefail

dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable NetworkManager
dnf install --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable -y cockpit* #cockpit-machines cockpit-podman cockpit-files cockpit-navigator cockpit-selinux

dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable podman podman-compose

systemctl enable cockpit.socket || true
#systemctl enable libvirtd || true
#systemctl enable httpd.service || true

rpm -qa | sort | grep cockpit
