#!/bin/bash
set -ouex pipefail

# DNF auto updates
sed -i 's/#AutomaticUpdatePolicy=none/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf

# Repo cleanup
rm -rf /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:phracek:PyCharm.repo
rm -rf /etc/yum.repos.d/google-chrome.repo
rm -rf /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
rm -rf /etc/yum.repos.d/rpmfusion-nonfree-steam.repo

dnf remove -y \
firefox* \
gnome-shell-extension* \
gnome-tour \
yelp* \
gnome-software-rpm-ostree \
virtualbox-guest-additions \
malcontent-control \
fedora-chromium-config* \
toolbox

# rpm-fusion
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
adw-gtk3-theme


# /*
# Configure Updates
# */
#sed -i 's|^ExecStart=.*|ExecStart=/usr/bin/bootc update --quiet|' /usr/lib/systemd/system/bootc-fetch-apply-updates.service
#sed -i 's|^OnUnitInactiveSec=.*|OnUnitInactiveSec=7d\nPersistent=true|' /usr/lib/systemd/system/bootc-fetch-apply-updates.timer
#sed -i 's|#AutomaticUpdatePolicy.*|AutomaticUpdatePolicy=stage|' /etc/rpm-ostreed.conf
#sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf
cat /usr/lib/systemd/system/bootc-fetch-apply-updates.service

# Disable the automatic reboot on the update service for bootc
#mkdir -p /etc/systemd/system/bootc-fetch-apply-updates.service.d
#cat << EOF > /etc/systemd/system/bootc-fetch-apply-updates.service.d/10-no-apply.conf
#[Service]
#ExecStart=
#ExecStart=/usr/bin/bootc update --quiet
#EOF


# Flatpak setup
echo -e "[Unit]\nDescription=Update Flatpaks\n[Service]\nType=oneshot\nExecStart=/usr/bin/flatpak remote-modify --disable fedora ; /usr/bin/flatpak remote-modify --enable flathub ; /usr/bin/flatpak uninstall --unused -y --noninteractive ; /usr/bin/bash -c 'curl -sSL https://raw.githubusercontent.com/emblem-66/Linux-Stuff/refs/heads/main/flatpak.list | xargs -r flatpak install -y --noninteractive' ; /usr/bin/bash -c 'cat /var/home/$(whoami)/.flatpak-apps.list | xargs -r flatpak install -y --noninteractive' ; /usr/bin/flatpak update -y --noninteractive\n[Install]\nWantedBy=default.target\n" | tee /etc/systemd/system/flatpak-update.service
echo -e "[Unit]\nDescription=Update Flatpaks\n[Timer]\nOnCalendar=*:0/4\nPersistent=true\n[Install]\nWantedBy=timers.target\n" | tee /etc/systemd/system/flatpak-update.timer

# Morewaita Icons
git clone https://github.com/somepaulo/MoreWaita.git /usr/share/icons/MoreWaita/


#dnf install -y --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable podman podman-compose


#dnf install -y --allowerasing libavcodec-freeworld mesa*freeworld ffmpeg gstreamer*

# DELUGE https://idroot.us/install-deluge-fedora-42/
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
deluge
#systemctl enable deluge

dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
transmission
#systemctl enable transmission



# Jellyfin https://idroot.us/install-jellyfin-fedora-42/
dnf remove -y ffmpeg-free
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
jellyfin
#systemctl enable jellyfin
#firewall-cmd --permanent --add-service=jellyfin
#firewall-cmd --permanent --add-port=8096/tcp
#firewall-cmd --permanent --add-port=8920/tcp
#firewall-cmd --permanent --add-port=1900/udp
#dnf --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable -y libva libva-intel-driver
#dnf --setopt=install_weak_deps=False --nogpgcheck --skip-unavailable -y zram-generator
#systemctl enable systemd-zram-setup@zram0.service


# SAMBA https://idroot.us/install-samba-fedora-42/
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
samba samba-common samba-client
#systemctl enable smb nmb

# immich
dnf copr enable -y mbooth/immich
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
immich


# Tailscale
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
tailscale 
systemctl enable tailscaled.service || true 

# SSH
systemctl enable sshd.service || true 

# Cockpit - basic only
dnf install \
--assumeyes \
--skip-broken \
--skip-unavailable \
--setopt=install_weak_deps=False \
--nogpgcheck \
--allowerasing \
cockpit
systemctl enable cockpit.socket || true


# Gsettings
#gsettings set org.gnome.desktop.wm.preferences resize-with-right-button "true"

