name: test2

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
      - '**.list'

  workflow_dispatch:

#--------------------------------------------

#jobs:

#  build-base:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    env:
#      TARGET: emblem-66/test2
#    strategy:
#      matrix:
#        variant: [base]
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v4
#    - name: Login to ghcr.io
#      shell: bash
#      run: podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: Maximize build disk space (Only remove unwanted software)
#      uses: AdityaGarg8/remove-unwanted-software@v5
      #with:
      #  remove-android: 'true'
      #  remove-dotnet: 'true'
      #  remove-haskell: 'true'
      #  remove-codeql: 'true'
      #  remove-docker-images: 'true'
      #  remove-large-packages: 'true'
      #  remove-cached-tools: 'true'
      #  remove-swapfile: 'true'
#    - name: Build and Push Base Image
#      run: |
#        podman build -f Containerfile -t ghcr.io/$TARGET:${{ matrix.variant }} --target ${{ matrix.variant }} .
#        podman push ghcr.io/$TARGET:${{ matrix.variant }}

#  build-on-base:
#    needs: build-base
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    env:
#      TARGET: emblem-66/test2
#    strategy:
#      matrix:
#        variant: [desktop, server]
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v4
#    - name: Login to ghcr.io
#      shell: bash
#      run: podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: Maximize build disk space (Only remove unwanted software)
#      uses: AdityaGarg8/remove-unwanted-software@v5
      #with:
      #    remove-android: 'true'
      #    remove-dotnet: 'true'
      #    remove-haskell: 'true'
      #    remove-codeql: 'true'
      #    remove-docker-images: 'true'
      #    remove-large-packages: 'true'
      #    remove-cached-tools: 'true'
      #    remove-swapfile: 'true'
#    - name: Build and Push Base Image
#      run: |
#        podman build -f Containerfile -t ghcr.io/$TARGET:${{ matrix.variant }} --target ${{ matrix.variant }} .
#        podman push ghcr.io/$TARGET:${{ matrix.variant }}



#---

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TARGET: emblem-66/test2
    #  BASE: base
    strategy:
      matrix:
        variant: [base-bootc, base-arch, base-silverblue, base-fedora-ostree-desktops]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v4
    - name: Login to ghcr.io
      shell: bash
      run: podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Images
      run: |
        podman build -f Containerfile -t ghcr.io/$TARGET:${{ matrix.variant }} --target ${{ matrix.variant }} .
        podman push ghcr.io/$TARGET:${{ matrix.variant }}

  build-desktops:
    runs-on: ubuntu-latest
    needs: build-base
    permissions:
      contents: read
      packages: write
    env:
      TARGET: emblem-66/test2
    strategy:
      matrix:
        variant: [desktop-bootc, desktop-arch, desktop-silverblue, desktop-fedora-ostree-desktops]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v4
    - name: Build and Push Base Image
      shell: bash
      run: |
        podman build -f Containerfile -t ghcr.io/$TARGET:${{ matrix.variant }} --target ${{ matrix.variant }} .
    - name: Login to ghcr.io
      shell: bash
      run: |
        podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
        podman push ghcr.io/$TARGET:${{ matrix.variant }}

  build-server:
    runs-on: ubuntu-latest
    needs: build-base
    permissions:
      contents: read
      packages: write
    env:
      TARGET: emblem-66/test2
    strategy:
      matrix:
        variant: [server-bootc, server-arch, server-silverblue, server-fedora-ostree-desktops]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v4
    - name: Login Build and Push Server Images to ghcr.io
      shell: bash
      run: |
        podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
        podman build -f Containerfile -t ghcr.io/$TARGET:${{ matrix.variant }} --target ${{ matrix.variant }} .
        podman push ghcr.io/$TARGET:${{ matrix.variant }}
